### ISSUE TITLE
Snap build fails with '.../release/bundle' is not a directory

### ISSUE THREAD

**Issue by BorisMomot** [canonical/flutter-snap#31] opened 2021-03-03 06:46 UTC
It looks like snapcraft miss 'x64' in the path

It fails with this log:

The flutter plugin is currently in beta, its API may break. Use at your own risk.
The following snaps are required but not installed as snapcraft is running inside docker or podman container: flutter/latest/stable, core18.
Please ensure the environment is properly setup before continuing.
Ignore this message if the appropriate measures have already been taken
Pulling flutter-extension 
Switching to flutter channel 'dev'...
git: From https://github.com/flutter/flutter
git:  * [new branch]            flutter-1.27-candidate.10 -> origin/flutter-1.27-candidate.10
git:    9964e8fe38..97295dc9a8  master     -> origin/master
git: Already on 'dev'
git: Your branch is up to date with 'origin/dev'.
Successfully switched to flutter channel 'dev'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
Setting "enable-linux-desktop" value to "true".

You may need to restart any open editors for them to read new settings.
Flutter is already up to date on channel dev
Flutter 1.27.0-8.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision b7d4806243 (12 days ago) • 2021-02-19 09:22:45 -0800
Engine • revision 6993cb229b
Tools • Dart 2.13.0 (build 2.13.0-30.0.dev)
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.27.0-8.0.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
Pulling gnome-3-28-extension 
Pulling super-cool-app 
Cloning into '/build/parts/super-cool-app/src'...
Building flutter-extension 
Building gnome-3-28-extension 
mkdir -p x86_64-linux-gnu
gcc -Wall -O2 -o x86_64-linux-gnu/bindtextdomain.so -fPIC -shared ./../src/bindtextdomain.c -ldl
install -d /build/parts/gnome-3-28-extension/install/gnome-platform
install -d /build/parts/gnome-3-28-extension/install/data-dir
install -d /build/parts/gnome-3-28-extension/install/data-dir/icons
install -d /build/parts/gnome-3-28-extension/install/data-dir/sounds
install -d /build/parts/gnome-3-28-extension/install/data-dir/themes
install -D -m755 desktop-launch "/build/parts/gnome-3-28-extension/install/snap/command-chain"/desktop-launch
install -D -m644 x86_64-linux-gnu/bindtextdomain.so "/build/parts/gnome-3-28-extension/install/lib"/x86_64-linux-gnu/bindtextdomain.so
install -D -m755 hooks-configure-desktop "/build/parts/gnome-3-28-extension/install/snap/command-chain"/hooks-configure-desktop
make -j4
make install DESTDIR=/build/parts/gnome-3-28-extension/install
Building super-cool-app 
Running "flutter pub get" in build...                            2,259ms
[  +72 ms] executing: uname -m
[  +35 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +15 ms] executing: [/home/developer/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b7d4806243a4e906bf061f79a0e314ba28111aa6
[        ] executing: [/home/developer/flutter/] git tag --points-at b7d4806243a4e906bf061f79a0e314ba28111aa6
[  +10 ms] Exit code 0 from: git tag --points-at b7d4806243a4e906bf061f79a0e314ba28111aa6
[        ] 1.27.0-8.0.pre
[  +48 ms] executing: [/home/developer/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/developer/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +39 ms] executing: [/home/developer/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +67 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +41 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +54 ms] Skipping pub get: version match.
[ +134 ms] Building without sound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +5 ms] add_custom_command() missing VERBATIM or FLUTTER_TARGET_PLATFORM, updating.
[   +4 ms] Building Linux application...
[  +41 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64 /build/parts/super-cool-app/build/linux
[ +864 ms] -- The CXX compiler identification is Clang 6.0.0
[  +69 ms] -- Check for working CXX compiler: /usr/bin/clang++
[ +151 ms] -- Check for working CXX compiler: /usr/bin/clang++ -- works
[  +25 ms] -- Detecting CXX compiler ABI info
[ +129 ms] -- Detecting CXX compiler ABI info - done
[  +59 ms] -- Detecting CXX compile features
[   +2 ms] -- Detecting CXX compile features - done
[  +43 ms] -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
[   +3 ms] -- Checking for module 'gtk+-3.0'
[  +22 ms] --   Found gtk+-3.0, version 3.22.30
[  +89 ms] -- Checking for module 'glib-2.0'
[  +16 ms] --   Found glib-2.0, version 2.56.4
[  +27 ms] -- Checking for module 'gio-2.0'
[  +16 ms] --   Found gio-2.0, version 2.56.4
[  +45 ms] -- Configuring done
[  +39 ms] -- Generating done
[   +2 ms] -- Build files have been written to: /build/parts/super-cool-app/build/build/linux/x64/release
[   +6 ms] executing: ninja -C build/linux/x64/release install
[   +5 ms] ninja: Entering directory `build/linux/x64/release'
[+25956 ms] [1/6] Generating /build/parts/super-cool-app/build/linux/flutter/ephemeral/libflutter_linux_gtk.so, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_value.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/fl_view.h, /build/parts/super-cool-app/build/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[        ] [  +74 ms] executing: uname -m
[        ] [  +35 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +14 ms] executing: [/home/developer/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] b7d4806243a4e906bf061f79a0e314ba28111aa6
[        ] [        ] executing: [/home/developer/flutter/] git tag --points-at b7d4806243a4e906bf061f79a0e314ba28111aa6
[        ] [  +11 ms] Exit code 0 from: git tag --points-at b7d4806243a4e906bf061f79a0e314ba28111aa6
[        ] [        ] 1.27.0-8.0.pre
[        ] [  +47 ms] executing: [/home/developer/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/dev
[        ] [        ] executing: [/home/developer/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +40 ms] executing: [/home/developer/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [  +62 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +55 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +77 ms] Initializing file store
[        ] [  +25 ms] Skipping target: gen_localizations
[        ] [   +7 ms] unpack_linux: Starting due to {}
[        ] [+1244 ms] kernel_snapshot: Starting due to {}
[        ] [   +3 ms] unpack_linux: Complete
[   +1 ms] [ +890 ms] /home/developer/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/developer/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/developer/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --packages /build/parts/super-cool-app/build/.dart_tool/package_config.json --output-dill /build/parts/super-cool-app/build/.dart_tool/flutter_build/4864a7af3f086f3a737a3b50a4446af8/app.dill --depfile /build/parts/super-cool-app/build/.dart_tool/flutter_build/4864a7af3f086f3a737a3b50a4446af8/kernel_snapshot.d package:super_cool_app/main.dart
[        ] [+14954 ms] kernel_snapshot: Complete
[        ] [ +346 ms] aot_elf_release: Starting due to {InvalidatedReason.inputChanged}
[        ] [   +7 ms] executing: /home/developer/flutter/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot --deterministic --snapshot_kind=app-aot-elf --elf=/build/parts/super-cool-app/build/.dart_tool/flutter_build/4864a7af3f086f3a737a3b50a4446af8/app.so --strip /build/parts/super-cool-app/build/.dart_tool/flutter_build/4864a7af3f086f3a737a3b50a4446af8/app.dill
[        ] [+6307 ms] aot_elf_release: Complete
[        ] [  +29 ms] linux_aot_bundle: Starting due to {InvalidatedReason.inputChanged}
[        ] [   +3 ms] linux_aot_bundle: Complete
[        ] [  +28 ms] release_bundle_linux-x64_assets: Starting due to {}
[        ] [ +225 ms] release_bundle_linux-x64_assets: Complete
[        ] [  +32 ms] Persisting file store
[        ] [   +7 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [  +10 ms] "flutter assemble" took 24,285ms.
[   +2 ms] [  +36 ms] ensureAnalyticsSent: 32ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[+2657 ms] [2/6] Building CXX object CMakeFiles/super_cool_app.dir/main.cc.o
[        ] [3/6] Building CXX object CMakeFiles/super_cool_app.dir/flutter/generated_plugin_registrant.cc.o
[  +67 ms] [4/6] Building CXX object CMakeFiles/super_cool_app.dir/my_application.cc.o
[ +620 ms] [5/6] Linking CXX executable super_cool_app
[        ] [5/6] Install the project...
[   +3 ms] -- Install configuration: "Release"
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/super_cool_app
[        ] -- Set runtime path of "/build/parts/super-cool-app/build/build/linux/x64/release/bundle/super_cool_app" to "$ORIGIN/lib"
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/icudtl.dat
[   +8 ms] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/lib/libflutter_linux_gtk.so
[  +50 ms] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/packages
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/version.json
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/fonts
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/data/flutter_assets/NOTICES
[        ] -- Installing: /build/parts/super-cool-app/build/build/linux/x64/release/bundle/lib/libapp.so
[  +16 ms] Building Linux application... (completed in 31.1s)
[   +1 ms] "flutter linux" took 31,408ms.
[  +45 ms] ensureAnalyticsSent: 42ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
flutter pub get
flutter build linux --release -v -t lib/main.dart
'/build/parts/super-cool-app/build/build/linux/release/bundle' is not a directory

**Comment by MarcusTomlinson** [comment] 2021-03-03 06:58
Duplicate of: https://github.com/canonical/flutter-snap/issues/29

See: https://github.com/canonical/flutter-snap/issues/29#issuecomment-785733894

**Closed by MarcusTomlinson** 2021-03-03 06:58 UTC
