### ISSUE TITLE
`flutter run -d chrome` fails fails for some users and throw an exception

### ISSUE THREAD

**Issue by TahaTesser** [canonical/flutter-snap#28] opened 2021-02-01 09:07 UTC
Please check out 
https://github.com/flutter/flutter/issues/73976
https://github.com/flutter/flutter/issues/75073
https://github.com/flutter/flutter/issues/74985
Thank you

**Comment by MarcusTomlinson** [comment] 2021-02-01 09:09
Duplicate of https://github.com/canonical/flutter-snap/issues/23

**Closed by MarcusTomlinson** 2021-02-01 09:09 UTC
