### ISSUE TITLE
Flutter builds fail on 21.04

### ISSUE THREAD

**Issue by kenvandine** [canonical/flutter-snap#36] opened 2021-03-11 04:25 UTC
I'm seeing a new build failure when building on hirsute

I've reproduced the same issue with a new flutter project.  I've also attempted to stage libgcrypt20-dev in the flutter snap with no luck.  Here's the verbose build output:

ken@t14:~/src/github/flutter/foobar$ flutter build -v linux
[  +44 ms] executing: uname -m
[  +22 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +9 ms] executing: [/home/ken/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] executing: [/home/ken/snap/flutter/common/flutter/] git tag --points-at cc9b78fc5c4a4d2d51316d9626523336230a89a9
[  +10 ms] Exit code 0 from: git tag --points-at cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] 2.1.0-10.0.pre
[  +32 ms] executing: [/home/ken/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/ken/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +27 ms] Unable to locate an Android SDK.
[   +3 ms] executing: [/home/ken/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +44 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +49 ms] Skipping pub get: version match.
[  +86 ms] Generating /home/ken/src/github/flutter/foobar/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +40 ms] Building without sound null safety
[   +1 ms] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +4 ms] Building Linux application...
[  +12 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64
/home/ken/src/github/flutter/foobar/linux
[ +117 ms] -- The CXX compiler identification is Clang 6.0.0
[        ] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[  +61 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- works
[        ] -- Detecting CXX compiler ABI info
[  +62 ms] -- Detecting CXX compiler ABI info - done
[   +3 ms] -- Detecting CXX compile features
[ +263 ms] -- Detecting CXX compile features - done
[   +4 ms] -- Found PkgConfig: /snap/flutter/current/usr/bin/pkg-config (found version "0.29.1") 
[        ] -- Checking for module 'gtk+-3.0'
[  +14 ms] --   Found gtk+-3.0, version 3.22.30
[  +53 ms] -- Checking for module 'glib-2.0'
[  +11 ms] --   Found glib-2.0, version 2.56.4
[  +30 ms] -- Checking for module 'gio-2.0'
[  +10 ms] --   Found gio-2.0, version 2.56.4
[  +32 ms] -- Checking for module 'blkid'
[  +10 ms] --   Found blkid, version 2.31.1
[  +31 ms] -- Checking for module 'liblzma'
[  +12 ms] --   Found liblzma, version 5.2.2
[  +35 ms] -- Configuring done
[   +5 ms] -- Generating done
[        ] -- Build files have been written to: /home/ken/src/github/flutter/foobar/build/linux/x64/release
[   +6 ms] executing: ninja -C build/linux/x64/release install
[   +8 ms] ninja: Entering directory `build/linux/x64/release'
[+15278 ms] [1/6] Generating /home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +3 ms] [  +43 ms] executing: uname -m
[        ] [  +22 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +8 ms] executing: [/home/ken/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] [        ] executing: [/home/ken/snap/flutter/common/flutter/] git tag --points-at cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] [   +7 ms] Exit code 0 from: git tag --points-at cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] [        ] 2.1.0-10.0.pre
[        ] [  +33 ms] Unable to locate an Android SDK.
[        ] [   +3 ms] executing: [/home/ken/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [  +33 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +26 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +45 ms] Initializing file store
[        ] [  +15 ms] Skipping target: gen_localizations
[        ] [   +3 ms] unpack_linux: Starting due to {}
[        ] [  +38 ms] kernel_snapshot: Starting due to {}
[        ] [   +1 ms] unpack_linux: Complete
[   +1 ms] [ +587 ms] /home/ken/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/ken/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/ken/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter
--no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --packages
/home/ken/src/github/flutter/foobar/.dart_tool/package_config.json --output-dill
/home/ken/src/github/flutter/foobar/.dart_tool/flutter_build/c5adb77542f74390249588af50b80053/app.dill --depfile
/home/ken/src/github/flutter/foobar/.dart_tool/flutter_build/c5adb77542f74390249588af50b80053/kernel_snapshot.d package:foobar/main.dart
[   +1 ms] [+9443 ms] kernel_snapshot: Complete
[        ] [ +225 ms] aot_elf_release: Starting due to {InvalidatedReason.inputChanged}
[        ] [   +4 ms] executing: /home/ken/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot --deterministic
--snapshot_kind=app-aot-elf --elf=/home/ken/src/github/flutter/foobar/.dart_tool/flutter_build/c5adb77542f74390249588af50b80053/app.so --strip
/home/ken/src/github/flutter/foobar/.dart_tool/flutter_build/c5adb77542f74390249588af50b80053/app.dill
[        ] [+4106 ms] aot_elf_release: Complete
[        ] [  +22 ms] linux_aot_bundle: Starting due to {InvalidatedReason.inputChanged}
[        ] [   +2 ms] linux_aot_bundle: Complete
[        ] [  +19 ms] release_bundle_linux-x64_assets: Starting due to {}
[        ] [  +67 ms] release_bundle_linux-x64_assets: Complete
[        ] [  +23 ms] Persisting file store
[        ] [   +4 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [   +6 ms] "flutter assemble" took 14,662ms.
[        ] [  +71 ms] ensureAnalyticsSent: 68ms
[        ] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +251 ms] [2/6] Building CXX object CMakeFiles/foobar.dir/flutter/generated_plugin_registrant.cc.o
[   +4 ms] [3/6] Building CXX object CMakeFiles/foobar.dir/main.cc.o
[  +40 ms] [4/6] Building CXX object CMakeFiles/foobar.dir/my_application.cc.o
[  +68 ms] [5/6] Linking CXX executable intermediates_do_not_run/foobar
[        ] FAILED: intermediates_do_not_run/foobar 
[   +5 ms] : && /snap/flutter/current/usr/bin/clang++  -O3 -DNDEBUG  -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/  -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/  -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/ CMakeFiles/foobar.dir/main.cc.o
CMakeFiles/foobar.dir/my_application.cc.o CMakeFiles/foobar.dir/flutter/generated_plugin_registrant.cc.o  -o intermediates_do_not_run/foobar
-L/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral -Wl,-rpath,/home/ken/src/github/flutter/foobar/linux/flutter/ephemeral:
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so -lflutter_linux_gtk
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libblkid.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/liblzma.so && :
[   +1 ms] /snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE
(5) type: 0xc0008002
[   +1 ms] /snap/flutter/current/usr/bin/ld: warning: //lib/i386-linux-gnu/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
[        ] /snap/flutter/current/usr/bin/ld: warning: //usr/lib/i386-linux-gnu/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
[        ] /snap/flutter/current/usr/bin/ld: warning: //lib/x86_64-linux-gnu/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
[        ] //lib/x86_64-linux-gnu/libgcrypt.so.20: undefined reference to `fstat@GLIBC_2.33'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ] ninja: build stopped: subcommand failed.
[  +10 ms] Building Linux application... (completed in 16.5s)
[        ] "flutter linux" took 16,718ms.
[   +4 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:186:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:78:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:88:5)
           <asynchronous suspension>
           #4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1186:12)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1037:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #7      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #14     run.<anonymous closure> (package:flutter_tools/runner.dart:60:12)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #16     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #17     runInContext (package:flutter_tools/src/context_runner.dart:77:10)
           <asynchronous suspension>
           #18     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[  +75 ms] ensureAnalyticsSent: 74ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by kenvandine** [comment] 2021-03-11 04:27
Output of flutter doctor: 

[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-10.0.pre at /home/ken/snap/flutter/common/flutter
    • Framework revision cc9b78fc5c (13 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

**Comment by kenvandine** [comment] 2021-03-11 04:29
Same failure with flutter master:

[✓] Flutter (Channel master, 2.1.0-11.0.pre.205, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.205 at /home/ken/snap/flutter/common/flutter
    • Framework revision 267f66a7dc (14 minutes ago), 2021-03-10 23:15:03 -0500
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

**Comment by MarcusTomlinson** [comment] 2021-03-11 07:20
Looks related to: https://github.com/canonical/flutter-snap/issues/32

We may need libgcrypt added to the CMake boilerplate upstream. Will have a look today.

**Comment by MarcusTomlinson** [comment] 2021-03-11 17:16
Duplicate of https://github.com/canonical/flutter-snap/issues/32.

**Closed by MarcusTomlinson** 2021-03-11 17:16 UTC
